image: maven:3.9.0-eclipse-temurin-17

stages:
  - clean-compile
  - test
  - build
  - release

variables:
  GITLAB_TOKEN: "glpat-gmtp2CsLFQGZp68WEvBG"

install-commons:
  stage: clean-compile
  script:
    - git clone https://oauth2:${GITLAB_TOKEN}@gitlab.com/jala-university1/cohort-4/oficial-es-desarrollo-de-software-2-cssd-125.ga.t1.25.m2/secci-n-a/capstone/commons-module.git
    - cd commons-module
    - mvn $MAVEN_CLI_OPTS clean install
  artifacts:
    paths:
      - .m2/repository
    expire_in: 1 hour

install-account:
  stage: clean-compile
  needs: ['install-commons']
  script:
    - git clone https://oauth2:${GITLAB_TOKEN}@gitlab.com/jala-university1/cohort-4/oficial-es-desarrollo-de-software-2-cssd-125.ga.t1.25.m2/secci-n-a/capstone/account-module.git
    - cd account-module
    - mvn $MAVEN_CLI_OPTS clean install
  artifacts:
    paths:
      - .m2/repository
    expire_in: 1 hour

external-payment-compile:
  stage: clean-compile
  needs: ['install-account', 'install-commons']
  script:
    - git clone https://oauth2:${GITLAB_TOKEN}@gitlab.com/jala-university1/cohort-4/oficial-es-desarrollo-de-software-2-cssd-125.ga.t1.25.m2/secci-n-a/capstone/external-payment-module.git
    - cd external-payment-module
    - mvn $MAVEN_CLI_OPTS clean compile

external-payment-test:
  stage: test
  needs: ['external-payment-compile']
  script:
    - cd external-payment-module
    - mvn $MAVEN_CLI_OPTS test

external-payment-build:
  stage: build
  needs: ['external-payment-compile', 'external-payment-test']
  script:
    - cd external-payment-module
    - mvn $MAVEN_CLI_OPTS package
  artifacts:
    paths:
      - external-payment-module/target/*.jar
    expire_in: 30 days
