default:
  image: maven:3.9.4-eclipse-temurin-17

stages:
  - build
  - test
  - analyze

variables:
  MAVEN_CLI_OPTS: "-B"

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile
  only:
    - merge_requests

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/TEST-*.xml
  only:
    - merge_requests

analyze:
  stage: analyze
  script:
    - mvn $MAVEN_CLI_OPTS checkstyle:checkstyle
  artifacts:
    paths:
      - target/checkstyle-result.xml
  only:
    - merge_requests
